name: Release

on:
    release:
        types: published
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Checkout
              run: git checkout master
            - name: Setup NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - name: Install vsce
              run: npm i -g vsce
            - name: Install
              run: npm i
            - name: Lint
              run: npm run lint

            # - name: Test
            #   run: xvfb-run npm t
            - name: Build
              run: vsce package
            - name: Publish to marketplace
              run: echo ${{ github.ref }} | cut -c 11- | xargs vsce publish
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Upload asset
              run: cd releaseScripts && npm i && node uploadReleaseAsset.js
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
